# Author: Saba Mansourfar 
# University: Politecnico Di Milano
# Labratory: NearLAB
#     Robot: Kuka LWR 4+

#  **Important Notice**
#  This will load default Kuka controllers + some specific controllers

KUKA:
  # CONTROLLERS USED
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # THIS CONFIGURATION IS ACTUALLY SENDING TAU = K*Q
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - KUKA_a1_joint
      - KUKA_a2_joint
      - KUKA_a3_joint
      - KUKA_a4_joint
      - KUKA_a5_joint
      - KUKA_a6_joint
      - KUKA_a7_joint
      - KUKA_a8_joint

## OTHER CUSTOM CONTROLLERS LEFT HERE AS EXAMPLES
  arm_state_controller: 
    type: arm_state_controller/ArmStateController
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    publish_rate: 30

  gravity_compensation_controller:
    type: KUKA_controllers/GravityCompensation
    root_name: KUKA_base_link
    tip_name: KUKA_8_link

  #   Joint Impedance Controllers
  joint_impedance_controller:
    type: KUKA_controllers/JointImpedanceController
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    stiffness_gains: 300
    damping_gains: .7

  # Inverse Dynamics Controllers
  inverse_dynamics_controller:
    type: KUKA_controllers/InverseDynamicsController
    root_name: KUKA_base_link
    tip_name: KUKA_8_link

  # Computed Torque Controllers
  computed_torque_controller:
    type: KUKA_controllers/ComputedTorqueController
    root_name: KUKA_base_link
    tip_name: KUKA_8_link

  # One Task Inverse Kinematics
  one_task_inverse_kinematics:
    type: KUKA_controllers/OneTaskInverseKinematics
    root_name: KUKA_base_link
    tip_name: KUKA_8_link

  # Cartesian Impedance
  cartesian_impedance_controller:
    type: KUKA_controllers/CartesianImpedanceController
    robot_name: KUKA
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    publish_cartesian_pose: false

  # Multi Task Priority Inverse Kinematics
  multi_task_priority_inverse_kinematics:
    type: KUKA_controllers/MultiTaskPriorityInverseKinematics
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    pid_KUKA_a1_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a2_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a3_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a4_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a5_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a6_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a7_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a8_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # One Task Inverse Dynamics JL
  one_task_inverse_dynamics_JL:
    type: KUKA_controllers/OneTaskInverseDynamicsJL
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    pid_KUKA_a1_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a2_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a3_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a4_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a5_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a6_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a7_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a8_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # Multi Task Priority Inverse Dynamics
  multi_task_priority_inverse_dynamics:
    type: KUKA_controllers/MultiTaskPriorityInverseDynamics
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    pid_KUKA_a1_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a2_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a3_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a4_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a5_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a6_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a7_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a8_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # Minimum Effort Inverse Dynamics
  minimum_effort_inverse_dynamics:
    type: KUKA_controllers/MinimumEffortInverseDynamics
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    pid_KUKA_a1_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a2_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a3_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a4_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a5_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a6_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a7_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a8_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # Backstepping Controller
  back_stepping_controller:
    type: KUKA_controllers/BacksteppingController
    root_name: KUKA_base_link
    tip_name: KUKA_8_link
    pid_KUKA_a1_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a2_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a3_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a4_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a5_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a6_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a7_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_KUKA_a8_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # Dynamic Sliding Mode Controller
  dynamics_sliding_mode_controller:
     type: KUKA_controllers/DynamicSlidingModeController
     root_name: KUKA_base_link
     tip_name: KUKA_8_link
     pid_KUKA_a1_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a2_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a3_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a4_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a5_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a6_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a7_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a8_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # Dynamic Sliding Mode Controller Task Space
  dynamics_sliding_mode_controller_task_space_controller:
     type: KUKA_controllers/DynamicSlidingModeControllerTaskSpace
     root_name: KUKA_base_link
     tip_name: KUKA_8_link
     pid_KUKA_a1_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a2_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a3_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a4_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a5_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a6_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a7_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
     pid_KUKA_a8_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
